<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:meta="https://api.nav.gov.hu/definitions/form_xsd_metaschema/1.0"
        xmlns:tns="https://soap.api.nav.gov.hu/definitions/model/2.0/2643TAO/1.0"
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        targetNamespace="https://soap.api.nav.gov.hu/definitions/model/2.0/2643TAO/1.0">
   <import namespace="https://api.nav.gov.hu/definitions/form_xsd_metaschema/1.0"
           schemaLocation="form_xsd_metaschema.xsd"/>
   <element name="Doc_2643TAO"
            type="tns:Doc_2643TAO_Type"
            meta:metaType="DocMetaType">
      <annotation>
         <documentation>Bevallás a kisvállalati adó hatálya alól kikerült, 2026-ban a társasági adó alanyává vált adózó társaságiadó-előlegéről</documentation>
      </annotation>
   </element>
   <complexType name="Doc_2643TAO_Type">
      <annotation>
         <documentation>A teljes bizonylat szerkezetet leíró típus</documentation>
      </annotation>
      <sequence>
         <element name="Form_2643TAO"
                  type="tns:Form_2643TAO_Type"
                  minOccurs="1"
                  maxOccurs="1"
                  meta:metaType="FormMetaType">
            <annotation>
               <documentation>2643TAO részbizonylat</documentation>
            </annotation>
         </element>
      </sequence>
   </complexType>
   <complexType name="Form_2643TAO_Type">
      <annotation>
         <documentation>A teljes nyomtatvány 2643TAO részbiztonylatának szerkezetét leíró típus.</documentation>
      </annotation>
      <sequence>
         <element name="Block_120001"
                  type="tns:Block_2643TAO_120001_Type"
                  minOccurs="0"
                  meta:metaType="BlockMetaType">
            <annotation>
               <documentation>Azonosító adatok</documentation>
            </annotation>
         </element>
         <element name="Block_120009"
                  type="tns:Block_2643TAO_120009_Type"
                  minOccurs="0"
                  meta:metaType="BlockMetaType">
            <annotation>
               <documentation>A KIVA-alanyiság megszűnését követő társaságiadó-előleg bevallása</documentation>
            </annotation>
         </element>
      </sequence>
   </complexType>
   <complexType name="Block_2643TAO_120001_Type">
      <annotation>
         <documentation>Azonosító adatok</documentation>
      </annotation>
      <all>
         <element name="FieldGroup_120002"
                  type="tns:FieldGroup_2643TAO_120002_Type"
                  minOccurs="0"
                  meta:metaType="FieldGroupMetaType">
            <annotation>
               <documentation>Adózó adatai</documentation>
            </annotation>
         </element>
         <element name="FieldGroup_120005"
                  type="tns:FieldGroup_2643TAO_120005_Type"
                  minOccurs="0"
                  meta:metaType="FieldGroupMetaType">
            <annotation>
               <documentation>Ügyintéző adatai</documentation>
            </annotation>
         </element>
         <element name="FieldGroup_120003"
                  type="tns:FieldGroup_2643TAO_120003_Type"
                  minOccurs="0"
                  meta:metaType="FieldGroupMetaType">
            <annotation>
               <documentation>Bevallás jellemzői</documentation>
            </annotation>
         </element>
      </all>
   </complexType>
   <complexType name="Block_2643TAO_120009_Type">
      <annotation>
         <documentation>A KIVA-alanyiság megszűnését követő társaságiadó-előleg bevallása</documentation>
      </annotation>
      <all>
         <element name="FieldGroup_120010"
                  type="tns:FieldGroup_2643TAO_120010_Type"
                  minOccurs="0"
                  meta:metaType="FieldGroupMetaType">
            <annotation>
               <documentation>(A) A társaságiadóelőleg-kötelezettség meghatározása</documentation>
            </annotation>
         </element>
         <element name="FieldGroup_120011"
                  type="tns:FieldGroup_2643TAO_120011_Type"
                  minOccurs="0"
                  meta:metaType="FieldGroupMetaType">
            <annotation>
               <documentation>(B) A társaságiadóelőleg-kötelezettség összege az előlegfizetési hónapokra</documentation>
            </annotation>
         </element>
      </all>
   </complexType>
   <complexType name="FieldGroup_2643TAO_120002_Type">
      <annotation>
         <documentation>Adózó adatai</documentation>
      </annotation>
      <all>
         <element name="Field_0A0001C001A"
                  minOccurs="0"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>Adószám (adószám)</documentation>
            </annotation>
            <simpleType>
               <restriction base="string">
                  <minLength value="1"/>
                  <maxLength value="11"/>
                  <pattern value="[0-9]+"/>
               </restriction>
            </simpleType>
         </element>
         <element name="Field_0A0001C003A"
                  minOccurs="0"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>Név (adozo_nev)</documentation>
            </annotation>
            <simpleType>
               <restriction base="string">
                  <minLength value="1"/>
                  <maxLength value="80"/>
                  <pattern value="\P{C}+"/>
               </restriction>
            </simpleType>
         </element>
      </all>
   </complexType>
   <complexType name="FieldGroup_2643TAO_120005_Type">
      <annotation>
         <documentation>Ügyintéző adatai</documentation>
      </annotation>
      <all>
         <element name="Field_0A0001C004A"
                  minOccurs="0"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>Név (ugyintezo_nev)</documentation>
            </annotation>
            <simpleType>
               <restriction base="string">
                  <minLength value="1"/>
                  <maxLength value="80"/>
                  <pattern value="\P{C}+"/>
               </restriction>
            </simpleType>
         </element>
         <element name="Field_0A0001C005A"
                  minOccurs="0"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>Telefonszám (ugyintezo_tel)</documentation>
            </annotation>
            <simpleType>
               <restriction base="string">
                  <minLength value="1"/>
                  <maxLength value="40"/>
                  <pattern value="\P{C}+"/>
               </restriction>
            </simpleType>
         </element>
      </all>
   </complexType>
   <complexType name="FieldGroup_2643TAO_120003_Type">
      <annotation>
         <documentation>Bevallás jellemzői</documentation>
      </annotation>
      <all>
         <element name="Field_0A0001D001A"
                  minOccurs="0"
                  type="xs:date"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>KIVA adóalanyiság megszűnésének napja (megszunesnap)</documentation>
            </annotation>
         </element>
         <element name="Field_0A0001D002A"
                  minOccurs="0"
                  type="xs:date"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>Bevallási időszak ¦ Kezdete (bevtol)</documentation>
            </annotation>
         </element>
         <element name="Field_0A0001D003A"
                  minOccurs="0"
                  type="xs:date"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>Bevallási időszak ¦ Vége (bevig)</documentation>
            </annotation>
         </element>
         <element name="Field_0A0001C002A"
                  minOccurs="0"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>Hibásnak minősített bevallás vonalkódja (vonalkod)</documentation>
            </annotation>
            <simpleType>
               <restriction base="string">
                  <minLength value="1"/>
                  <maxLength value="10"/>
                  <pattern value="[0-9]+"/>
               </restriction>
            </simpleType>
         </element>
      </all>
   </complexType>
   <complexType name="FieldGroup_2643TAO_120010_Type">
      <annotation>
         <documentation>(A) A társaságiadóelőleg-kötelezettség meghatározása</documentation>
      </annotation>
      <all>
         <element name="Field_0B0001C0001AA"
                  minOccurs="0"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>01. A 2025. adóévre elszámolt összes/évesített bevétel [Tao. Tv. 26. § (13) a)-b)] ([01]A1)</documentation>
            </annotation>
            <simpleType>
               <restriction base="string">
                  <minLength value="1"/>
                  <maxLength value="16"/>
                  <pattern value="[0-9]+"/>
               </restriction>
            </simpleType>
         </element>
         <element name="Field_0B0001C0002AA"
                  minOccurs="0"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>02. A 2026. adóévre elszámolt bevétel évesített összege [Tao. Tv. 26. § (13) b)] ([01]A2)</documentation>
            </annotation>
            <simpleType>
               <restriction base="string">
                  <minLength value="1"/>
                  <maxLength value="16"/>
                  <pattern value="[0-9]+"/>
               </restriction>
            </simpleType>
         </element>
         <element name="Field_0B0001C0003AA"
                  minOccurs="0"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>03. Az adóelőleg-kötelezettség összege (01. vagy 02. sor 0,25 százaléka) ([01]A3)</documentation>
            </annotation>
            <simpleType>
               <restriction base="string">
                  <minLength value="1"/>
                  <maxLength value="16"/>
                  <pattern value="[0-9]+"/>
               </restriction>
            </simpleType>
         </element>
      </all>
   </complexType>
   <complexType name="FieldGroup_2643TAO_120011_Type">
      <annotation>
         <documentation>(B) A társaságiadóelőleg-kötelezettség összege az előlegfizetési hónapokra</documentation>
      </annotation>
      <all>
         <element name="Field_0B0001D0004AA"
                  minOccurs="0"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>2026. március ([01]A4)</documentation>
            </annotation>
            <simpleType>
               <restriction base="string">
                  <minLength value="1"/>
                  <maxLength value="16"/>
                  <pattern value="[0-9]+"/>
               </restriction>
            </simpleType>
         </element>
         <element name="Field_0B0001D0005AA"
                  minOccurs="0"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>2026. június ([01]A5)</documentation>
            </annotation>
            <simpleType>
               <restriction base="string">
                  <minLength value="1"/>
                  <maxLength value="16"/>
                  <pattern value="[0-9]+"/>
               </restriction>
            </simpleType>
         </element>
         <element name="Field_0B0001D0006AA"
                  minOccurs="0"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>2026. szeptember ([01]A6)</documentation>
            </annotation>
            <simpleType>
               <restriction base="string">
                  <minLength value="1"/>
                  <maxLength value="16"/>
                  <pattern value="[0-9]+"/>
               </restriction>
            </simpleType>
         </element>
         <element name="Field_0B0001D0007AA"
                  minOccurs="0"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>2026. december ([01]A7)</documentation>
            </annotation>
            <simpleType>
               <restriction base="string">
                  <minLength value="1"/>
                  <maxLength value="16"/>
                  <pattern value="[0-9]+"/>
               </restriction>
            </simpleType>
         </element>
         <element name="Field_0B0001D0008AA"
                  minOccurs="0"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>2027. március ([01]A8)</documentation>
            </annotation>
            <simpleType>
               <restriction base="string">
                  <minLength value="1"/>
                  <maxLength value="16"/>
                  <pattern value="[0-9]+"/>
               </restriction>
            </simpleType>
         </element>
         <element name="Field_0B0001D0009AA"
                  minOccurs="0"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>2027. június ([01]A9)</documentation>
            </annotation>
            <simpleType>
               <restriction base="string">
                  <minLength value="1"/>
                  <maxLength value="16"/>
                  <pattern value="[0-9]+"/>
               </restriction>
            </simpleType>
         </element>
      </all>
   </complexType>
</schema>
